solucel_admin_adminsetting_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:AdminSetting:index" }
    methods:  GET

solucel_admin_adminsetting_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:AdminSetting:show" }
    methods:  GET

solucel_admin_adminsetting_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:AdminSetting:new" }
    #methods:  [GET, POST]
    
solucel_admin_adminsetting_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:AdminSetting:create" }
    requirements: { _method: post }


solucel_admin_adminsetting_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:AdminSetting:edit" }
    #methods:  [GET, POST]
    

solucel_admin_adminsetting_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:AdminSetting:update" }
    requirements: { _method: post|put }     

solucel_admin_adminsetting_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:AdminSetting:delete" }
    #methods:  DELETE
