solucel_admin_agency_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:Agency:index" }
    methods:  GET

solucel_admin_agency_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:Agency:show" }
    methods:  GET

solucel_admin_agency_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:Agency:new" }
    #methods:  [GET, POST]
    
solucel_admin_agency_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:Agency:create" }
    requirements: { _method: post }


solucel_admin_agency_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:Agency:edit" }
    #methods:  [GET, POST]
    

solucel_admin_agency_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:Agency:update" }
    requirements: { _method: post|put }     

solucel_admin_agency_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:Agency:delete" }
    #methods:  DELETE
