solucel_admin_country_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:Country:index" }
    methods:  GET

solucel_admin_country_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:Country:show" }
    methods:  GET

solucel_admin_country_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:Country:new" }
    #methods:  [GET, POST]
    
solucel_admin_country_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:Country:create" }
    requirements: { _method: post }


solucel_admin_country_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:Country:edit" }
    #methods:  [GET, POST]
    

solucel_admin_country_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:Country:update" }
    requirements: { _method: post|put }     

solucel_admin_country_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:Country:delete" }
    #methods:  DELETE
