solucel_admin_devicedefectcode_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceDefectCode:index" }
    methods:  GET

solucel_admin_devicedefectcode_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceDefectCode:show" }
    methods:  GET

solucel_admin_devicedefectcode_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceDefectCode:new" }
    #methods:  [GET, POST]
    
solucel_admin_devicedefectcode_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceDefectCode:create" }
    requirements: { _method: post }


solucel_admin_devicedefectcode_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceDefectCode:edit" }
    #methods:  [GET, POST]
    

solucel_admin_devicedefectcode_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceDefectCode:update" }
    requirements: { _method: post|put }     

solucel_admin_devicedefectcode_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceDefectCode:delete" }
    #methods:  DELETE
