solucel_admin_deviceaccessory_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceAccessory:index" }
    methods:  GET

solucel_admin_deviceaccessory_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceAccessory:show" }
    methods:  GET

solucel_admin_deviceaccessory_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceAccessory:new" }
    #methods:  [GET, POST]
    
solucel_admin_deviceaccessory_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceAccessory:create" }
    requirements: { _method: post }


solucel_admin_deviceaccessory_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceAccessory:edit" }
    #methods:  [GET, POST]
    

solucel_admin_deviceaccessory_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceAccessory:update" }
    requirements: { _method: post|put }     

solucel_admin_deviceaccessory_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceAccessory:delete" }
    #methods:  DELETE
