solucel_admin_devicefixtypecode_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceFixTypeCode:index" }
    methods:  GET

solucel_admin_devicefixtypecode_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceFixTypeCode:show" }
    methods:  GET

solucel_admin_devicefixtypecode_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceFixTypeCode:new" }
    #methods:  [GET, POST]
    
solucel_admin_devicefixtypecode_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceFixTypeCode:create" }
    requirements: { _method: post }


solucel_admin_devicefixtypecode_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceFixTypeCode:edit" }
    #methods:  [GET, POST]
    

solucel_admin_devicefixtypecode_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceFixTypeCode:update" }
    requirements: { _method: post|put }     

solucel_admin_devicefixtypecode_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceFixTypeCode:delete" }
    #methods:  DELETE
