solucel_admin_devicecondition_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceCondition:index" }
    methods:  GET

solucel_admin_devicecondition_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceCondition:show" }
    methods:  GET

solucel_admin_devicecondition_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceCondition:new" }
    #methods:  [GET, POST]
    
solucel_admin_devicecondition_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceCondition:create" }
    requirements: { _method: post }


solucel_admin_devicecondition_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceCondition:edit" }
    #methods:  [GET, POST]
    

solucel_admin_devicecondition_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceCondition:update" }
    requirements: { _method: post|put }     

solucel_admin_devicecondition_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceCondition:delete" }
    #methods:  DELETE
