solucel_admin_devicelocation_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceLocation:index" }
    methods:  GET

solucel_admin_devicelocation_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceLocation:show" }
    methods:  GET

solucel_admin_devicelocation_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceLocation:new" }
    #methods:  [GET, POST]
    
solucel_admin_devicelocation_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceLocation:create" }
    requirements: { _method: post }


solucel_admin_devicelocation_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceLocation:edit" }
    #methods:  [GET, POST]
    

solucel_admin_devicelocation_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceLocation:update" }
    requirements: { _method: post|put }     

solucel_admin_devicelocation_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceLocation:delete" }
    #methods:  DELETE
