solucel_admin_devicebrand_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceBrand:index" }
    methods:  GET

solucel_admin_devicebrand_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceBrand:show" }
    methods:  GET

solucel_admin_devicebrand_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceBrand:new" }
    #methods:  [GET, POST]
    
solucel_admin_devicebrand_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceBrand:create" }
    requirements: { _method: post }


solucel_admin_devicebrand_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceBrand:edit" }
    #methods:  [GET, POST]
    

solucel_admin_devicebrand_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceBrand:update" }
    requirements: { _method: post|put }     

solucel_admin_devicebrand_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceBrand:delete" }
    #methods:  DELETE
