solucel_admin_devicereplacement_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacement:index" }
    methods:  GET

solucel_admin_devicereplacement_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacement:show" }
    methods:  GET

solucel_admin_devicereplacement_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacement:new" }
    #methods:  [GET, POST]
    
solucel_admin_devicereplacement_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacement:create" }
    requirements: { _method: post }


solucel_admin_devicereplacement_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacement:edit" }
    #methods:  [GET, POST]
    

solucel_admin_devicereplacement_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacement:update" }
    requirements: { _method: post|put }     

solucel_admin_devicereplacement_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacement:delete" }
    #methods:  DELETE
    
solucel_admin_devicereplacement_load:       
    path:     /load
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacement:load" }
    
replacement_list_datatables:
    path: /replacement/list/datatables
    defaults:
        _controller: SolucelAdminBundle:DeviceReplacement:listDatatables

