solucel_admin_devicemodel_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceModel:index" }
    methods:  GET

solucel_admin_devicemodel_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceModel:show" }
    methods:  GET

solucel_admin_devicemodel_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceModel:new" }
    #methods:  [GET, POST]
    
solucel_admin_devicemodel_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceModel:create" }
    requirements: { _method: post }


solucel_admin_devicemodel_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceModel:edit" }
    #methods:  [GET, POST]
    

solucel_admin_devicemodel_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceModel:update" }
    requirements: { _method: post|put }     

solucel_admin_devicemodel_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceModel:delete" }
    #methods:  DELETE
