solucel_admin_devicereplacementtype_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacementType:index" }
    methods:  GET

solucel_admin_devicereplacementtype_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacementType:show" }
    methods:  GET

solucel_admin_devicereplacementtype_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacementType:new" }
    #methods:  [GET, POST]
    
solucel_admin_devicereplacementtype_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacementType:create" }
    requirements: { _method: post }


solucel_admin_devicereplacementtype_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacementType:edit" }
    #methods:  [GET, POST]
    

solucel_admin_devicereplacementtype_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacementType:update" }
    requirements: { _method: post|put }     

solucel_admin_devicereplacementtype_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:DeviceReplacementType:delete" }
    #methods:  DELETE
