solucel_admin_originpoint_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:OriginPoint:index" }
    methods:  GET

solucel_admin_originpoint_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:OriginPoint:show" }
    methods:  GET

solucel_admin_originpoint_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:OriginPoint:new" }
    #methods:  [GET, POST]
    
solucel_admin_originpoint_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:OriginPoint:create" }
    requirements: { _method: post }


solucel_admin_originpoint_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:OriginPoint:edit" }
    #methods:  [GET, POST]
    

solucel_admin_originpoint_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:OriginPoint:update" }
    requirements: { _method: post|put }     

solucel_admin_originpoint_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:OriginPoint:delete" }
    #methods:  DELETE