solucel_admin_problemfoundcode_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:ProblemFoundCode:index" }
    methods:  GET

solucel_admin_problemfoundcode_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:ProblemFoundCode:show" }
    methods:  GET

solucel_admin_problemfoundcode_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:ProblemFoundCode:new" }
    #methods:  [GET, POST]
    
solucel_admin_problemfoundcode_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:ProblemFoundCode:create" }
    requirements: { _method: post }


solucel_admin_problemfoundcode_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:ProblemFoundCode:edit" }
    #methods:  [GET, POST]
    

solucel_admin_problemfoundcode_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:ProblemFoundCode:update" }
    requirements: { _method: post|put }     

solucel_admin_problemfoundcode_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:ProblemFoundCode:delete" }
    #methods:  DELETE
