solucel_admin_qualitycontrolgroup_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:QualityControlGroup:index" }
    methods:  GET

solucel_admin_qualitycontrolgroup_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:QualityControlGroup:show" }
    methods:  GET

solucel_admin_qualitycontrolgroup_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:QualityControlGroup:new" }
    #methods:  [GET, POST]
    
solucel_admin_qualitycontrolgroup_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:QualityControlGroup:create" }
    requirements: { _method: post }


solucel_admin_qualitycontrolgroup_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:QualityControlGroup:edit" }
    #methods:  [GET, POST]
    

solucel_admin_qualitycontrolgroup_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:QualityControlGroup:update" }
    requirements: { _method: post|put }     

solucel_admin_qualitycontrolgroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:QualityControlGroup:delete" }
    #methods:  DELETE
