solucel_admin_repairorderfixconfirmationlog_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:RepairOrderFixConfirmationLog:index" }
    methods:  GET

solucel_admin_repairorderfixconfirmationlog_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:RepairOrderFixConfirmationLog:show" }
    methods:  GET

solucel_admin_repairorderfixconfirmationlog_new:
    path:     /{orderFixID}/new
    defaults: { _controller: "SolucelAdminBundle:RepairOrderFixConfirmationLog:new" }
    methods:  [GET, POST]
    
solucel_admin_repairorderfixconfirmationlog_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:RepairOrderFixConfirmationLog:create" }
    requirements: { _method: post }
    

solucel_admin_repairorderfixconfirmationlog_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:RepairOrderFixConfirmationLog:edit" }
    methods:  [GET, POST]

solucel_admin_repairorderfixconfirmationlog_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:RepairOrderFixConfirmationLog:delete" }
    methods:  DELETE
