solucel_admin_repairentrytype_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:RepairEntryType:index" }
    methods:  GET

solucel_admin_repairentrytype_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:RepairEntryType:show" }
    methods:  GET

solucel_admin_repairentrytype_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:RepairEntryType:new" }
    #methods:  [GET, POST]
    
solucel_admin_repairentrytype_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:RepairEntryType:create" }
    requirements: { _method: post }


solucel_admin_repairentrytype_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:RepairEntryType:edit" }
    #methods:  [GET, POST]
    

solucel_admin_repairentrytype_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:RepairEntryType:update" }
    requirements: { _method: post|put }     

solucel_admin_repairentrytype_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:RepairEntryType:delete" }
    #methods:  DELETE