solucel_admin_repairstatus_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:RepairStatus:index" }
    methods:  GET

solucel_admin_repairstatus_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:RepairStatus:show" }
    methods:  GET

solucel_admin_repairstatus_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:RepairStatus:new" }
    #methods:  [GET, POST]
    
solucel_admin_repairstatus_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:RepairStatus:create" }
    requirements: { _method: post }


solucel_admin_repairstatus_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:RepairStatus:edit" }
    #methods:  [GET, POST]
    

solucel_admin_repairstatus_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:RepairStatus:update" }
    requirements: { _method: post|put }     

solucel_admin_repairstatus_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:RepairStatus:delete" }
    #methods:  DELETE