solucel_admin_role_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:Role:index" }
    methods:  GET

solucel_admin_role_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:Role:show" }
    methods:  GET

solucel_admin_role_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:Role:new" }
    #methods:  [GET, POST]
    
solucel_admin_role_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:Role:create" }
    requirements: { _method: post }


solucel_admin_role_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:Role:edit" }
    #methods:  [GET, POST]
    

solucel_admin_role_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:Role:update" }
    requirements: { _method: post|put }     

solucel_admin_role_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:Role:delete" }
    #methods:  DELETE
