solucel_admin_state_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:State:index" }
    methods:  GET

solucel_admin_state_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:State:show" }
    methods:  GET

solucel_admin_state_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:State:new" }
    #methods:  [GET, POST]
    
solucel_admin_state_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:State:create" }
    requirements: { _method: post }


solucel_admin_state_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:State:edit" }
    #methods:  [GET, POST]
    

solucel_admin_state_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:State:update" }
    requirements: { _method: post|put }     

solucel_admin_state_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:State:delete" }
    #methods:  DELETE
