solucel_admin_transactioncode_index:
    path:     /
    defaults: { _controller: "SolucelAdminBundle:TransactionCode:index" }
    methods:  GET

solucel_admin_transactioncode_show:
    path:     /{id}/show
    defaults: { _controller: "SolucelAdminBundle:TransactionCode:show" }
    methods:  GET

solucel_admin_transactioncode_new:
    path:     /new
    defaults: { _controller: "SolucelAdminBundle:TransactionCode:new" }
    #methods:  [GET, POST]
    
solucel_admin_transactioncode_create:
    path:     /create
    defaults: { _controller: "SolucelAdminBundle:TransactionCode:create" }
    requirements: { _method: post }


solucel_admin_transactioncode_edit:
    path:     /{id}/edit
    defaults: { _controller: "SolucelAdminBundle:TransactionCode:edit" }
    #methods:  [GET, POST]
    

solucel_admin_transactioncode_update:
    path:     /{id}/update
    defaults: { _controller: "SolucelAdminBundle:TransactionCode:update" }
    requirements: { _method: post|put }     

solucel_admin_transactioncode_delete:
    path:     /{id}/delete
    defaults: { _controller: "SolucelAdminBundle:TransactionCode:delete" }
    #methods:  DELETE
