Solucel\AdminBundle\Entity\ActionReasonCode:
    type: entity
    table: action_reason_code
    
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''

        code:
            type: string
            nullable: false
            length: 4
            options:
                fixed: false
                default: ''
      
    lifecycleCallbacks: {  }
