Solucel\AdminBundle\Entity\AdminSetting:
    type: entity
    repositoryClass: Solucel\AdminBundle\Repository\AdminSettingRepository
    table: admin_setting
    indexes:
      updated_by:
        columns:
          - updated_by
    id:
      id:
        type: integer
        nullable: false
        options:
          unsigned: true
        id: true
        generator:
          strategy: IDENTITY
    fields:
      entryEstimatedTime:
        type: integer
        nullable: false
        options:
          fixed: false
          default: 0

      updatedAt:
        type: datetime
        nullable: false
        options:
          default: '2001-01-01 00:00:00'
        column: updated_at

    manyToOne:

        updatedBy:
          targetEntity: User
          cascade: {  }
          fetch: LAZY
          mappedBy: null
          inversedBy: null
          joinColumns:
            updated_by:
              referencedColumnName: id
              onDelete: CASCADE
          orphanRemoval: true

    lifecycleCallbacks: {  }
