Solucel\AdminBundle\Entity\Agency:
    type: entity
    repositoryClass: Solucel\AdminBundle\Repository\AgencyRepository
    table: agency
    indexes:
        operator_id:
            columns:
                - operator_id
    
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '2001-01-01 00:00:00'
            column: created_at
            
    manyToOne:
        operator:
            targetEntity: Operator
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                operator_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true
    lifecycleCallbacks: {  }
