Solucel\AdminBundle\Entity\DeviceReplacementType:
    type: entity
    table: device_replacement_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
                default: ''
##ESTE ES EL PRODUCT TYPE                
        code:
            type: string
            nullable: false
            length: 4
            options:
                fixed: false
                default: ''                
    lifecycleCallbacks: {  }
