Solucel\AdminBundle\Entity\LoginLog:
  type: entity
  repositoryClass: Solucel\AdminBundle\Repository\LoginLogRepository
  table: login_log
  indexes:
    user_id:
      columns:
        - user_id

  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    action:
      type: string
      nullable: false
      length: 8
      options:
        fixed: false
        default: ''
    createdAt:
      type: datetime
      nullable: false
      options:
        default: '2001-01-01 00:00:00'
      column: created_at

  manyToOne:
    user:
      targetEntity: User
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
          onDelete: CASCADE
      orphanRemoval: true
  lifecycleCallbacks: {  }
