Solucel\AdminBundle\Entity\ModuleAccess:
    type: entity
    repositoryClass: Solucel\AdminBundle\Repository\ModuleAccessRepository
    table: module_access
    indexes:
        module_id:
            columns:
                - module_id
        role_id:
            columns:
                - role_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        canRead:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: can_read
        canWrite:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: can_write
    manyToOne:
        module:
            targetEntity: Module
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                module_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true
        role:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true
    lifecycleCallbacks: {  }
