Solucel\AdminBundle\Entity\Notification:
    type: entity
    repositoryClass: Solucel\AdminBundle\Repository\NotificationRepository
    table: notification
    indexes:
        fk_notification_3_idx:
            columns:
                - user_id
        fk_notification_4_idx:
            columns:
                - created_by
        fk_notification_6_idx:
            columns:
                - updated_by
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            fixed: false    
        enabled:
            type: boolean
            nullable: true
            column: enabled        
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        already_read:
            type: boolean
            nullable: false
            column: already_read
            default: 0        
            
    manyToOne:
        user:
            targetEntity: User
            inversedBy: notification
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    onUpdate: CASCADE                    
        createdBy:
            targetEntity: User
            inversedBy: notification
            joinColumns:
                created_by:
                    referencedColumnName: id
                    onDelete: CASCADE
                    onUpdate: CASCADE
        updatedBy:
            targetEntity: User
            inversedBy: notification
            joinColumns:
                updated_by:
                    referencedColumnName: id
                    onDelete: CASCADE
                    onUpdate: CASCADE                    
                                                                           
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]        
            