Solucel\AdminBundle\Entity\Payer:
    type: entity
    table: payer
    
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
                default: ''

        code:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
                default: ''
            column: code
      
    lifecycleCallbacks: {  }