Solucel\AdminBundle\Entity\RepairOrderAdditionalField:
    type: entity
    table: repair_order_additional_field
    indexes:
        repair_order_id:
            columns:
                - repair_order_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''
        value:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
                default: N/A
    manyToOne:
        repairOrder:
            targetEntity: RepairOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                repair_order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

    lifecycleCallbacks: {  }
