Solucel\AdminBundle\Entity\RepairOrderPhoto:
    type: entity
    table: repair_order_photo
    indexes:
        repair_order_id:
            columns:
                - repair_order_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''
        photoPath:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
                default: ''
            column: photo_path
        photoType:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: Otro
            column: photo_type
    manyToOne:
        repairOrder:
            targetEntity: RepairOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                repair_order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

    lifecycleCallbacks: {  }
