Solucel\AdminBundle\Entity\RepairOrderDeviceDefect:
    type: entity
    table: repair_order_device_defect
    indexes:
        device_defect_id:
            columns:
                - device_defect_id
        repair_order_id:
            columns:
                - repair_order_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
    manyToOne:
        deviceDefect:
            targetEntity: DeviceDefect
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                device_defect_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

        repairOrder:
            targetEntity: RepairOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                repair_order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

    lifecycleCallbacks: {  }
