Solucel\AdminBundle\Entity\RepairOrderDelivery:
    type: entity
    table: repair_order_delivery
    indexes:
        repair_order_id:
            columns:
                - repair_order_id
        delivery_from_agency:
            columns:
                - delivery_from_agency
        delivery_to_service_center:
            columns:
                - delivery_to_service_center
        delivery_from_service_center:
            columns:
                - delivery_from_service_center
        delivery_to_agency:
            columns:
                - delivery_to_agency                                                
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        
        deliveryStatus:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: En Transito
            column: delivery_status
      
        deliveryDateSent:
            type: datetime
            nullable: false
            options:
                default: '2001-01-01 00:00:00'
            column: delivery_date_sent
        deliveryDateReceived:
            type: datetime
            nullable: true
            options:
                default: '2001-01-01 00:00:00'
            column: delivery_date_received

    manyToOne:
        repairOrder:
            targetEntity: RepairOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                repair_order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

        deliveryFromAgency:
            targetEntity: Agency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                delivery_from_agency:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true 
        deliveryToServiceCenter:
            targetEntity: ServiceCenter
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                delivery_to_service_center:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true                          
        deliveryFromServiceCenter:
            targetEntity: ServiceCenter
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                delivery_from_service_center:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true 
        deliveryToAgency:
            targetEntity: Agency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                delivery_to_agency:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true               
    lifecycleCallbacks: {  }
