Solucel\AdminBundle\Entity\RepairLog:
    type: entity
    table: repair_log
    indexes:
        repair_order_id:
            columns:
                - repair_order_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        action:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''
        description:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
                default: N/A
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '2001-01-01 00:00:00'
            column: created_at
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

        repairOrder:
            targetEntity: RepairOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                repair_order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

    lifecycleCallbacks: {  }
