Solucel\AdminBundle\Entity\RepairOrderDeviceLocation:
    type: entity
    table: repair_order_device_location
    indexes:
        repair_order_id:
            columns:
                - repair_order_id
        device_location_id:
            columns:
                - device_location_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '2001-01-01 00:00:00'
            column: created_at
    manyToOne:
        repairOrder:
            targetEntity: RepairOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                repair_order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

        deviceLocation:
            targetEntity: DeviceLocation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                device_location_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true

    lifecycleCallbacks: {  }
