Solucel\AdminBundle\Entity\Role:
    type: entity
    table: role
    indexes:
        company_department_id:
            columns:
                - company_department_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
    manyToOne:
        companyDepartment:
            targetEntity: CompanyDepartment
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_department_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
