Solucel\AdminBundle\Entity\ServiceCenter:
    type: entity
    repositoryClass: Solucel\AdminBundle\Repository\ServiceCenterRepository
    table: service_center
    indexes:
        storehouse_id:
            columns:
                - storehouse_id    
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''             
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '2001-01-01 00:00:00'
            column: created_at
            
    manyToOne:
        storehouse:
            targetEntity: Storehouse
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                storehouse_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: true                          
    lifecycleCallbacks: {  }
