Solucel\AdminBundle\Entity\Storehouse:
    type: entity
    table: storehouse
    
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''
        storehouseCode:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
            column: storehouse_code                
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '2001-01-01 00:00:00'
            column: created_at        
    lifecycleCallbacks: {  }
