Solucel\AdminBundle\Entity\TimeLog:
  type: entity
  repositoryClass: Solucel\AdminBundle\Repository\TimeLogRepository
  table: time_log
  indexes:
    user_id:
      columns:
        - user_id
    repair_order_id:
      columns:
        - repair_order_id


  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    action:
      type: string
      nullable: false
      length: 8
      options:
        fixed: false
        default: ''
    logTimeMinutes:
          type: integer
          nullable: false
          options:
            unsigned: true
            default: 0
    createdAt:
      type: datetime
      nullable: false
      options:
        default: '2001-01-01 00:00:00'
      column: created_at

  manyToOne:
    repairOrder:
      targetEntity: RepairOrder
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        repair_order_id:
          referencedColumnName: id
          onDelete: CASCADE
      orphanRemoval: true

    user:
      targetEntity: User
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
          onDelete: CASCADE
      orphanRemoval: true
  lifecycleCallbacks: {  }
