security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider:             fos_userbundle
                login_path:           fos_user_security_login
                check_path:           fos_user_security_check
                #csrf_token_generator: security.csrf.token_manager
                #success_handler:      security.authentication.success_handler
                default_target_path: solucel_admin_homepage
            logout:
                path: fos_user_security_logout
                handlers: [solucel_logoutlistener]
                target: solucel_admin_homepage
            anonymous:    true
            remember_me:
                #key:      "%secret%"
                secret:    "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                user_provider: fos_userbundle
            switch_user: true

    access_control:
        - { path: ^/repairtracking, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/repairtrackingcheck, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER  }
